steps:
  # Build the container image using the docker cloud builder
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/peaceful-nation-399620/my-web-app:$COMMIT_SHA', './Assignment 1 Files']

  # Push the image to your artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/peaceful-nation-399620/my-web-app:$COMMIT_SHA']

options:
  logging: REGIONAL_USER_OWNED_BUCKET

# Create a Cloud Build Trigger
# This trigger will execute when a push occurs to the branch
triggers:
  - name: dc-bob-100805862
    description: Cloud Build Trigger
    event: push
    source:
      branch: '.*' 
    substitutions:
      _CLOUD_BUILD_CONFIG: cloudbuild.yaml
    filename: $_CLOUD_BUILD_CONFIG
    build: 
      # Require approval before build execution
      approvalConfig:
        approvalRequired: true
